# Generated by Django 4.2.6 on 2023-10-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='photo',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
